### ISSUE TITLE
README needs a newline

### ISSUE THREAD

**Issue by Fernan2** [valenciarb/old.valenciarb.github.io#13]
The line I added, "Join the ValenciaDevs slack and find us on the #valenciarb channel", appears on the same line than "Twitter handle: https://twitter.com/valenciarb", I don't know why... :-(

**Comment by esebastian** [comment]
Did you tested it your local environment?

**Comment by carlescliment** [comment]
Have you tried putting a blank line above the one you added?

**Comment by Fernan2** [comment]
I don't have markdown viewers... :-(

**Comment by carlescliment** [comment]
C'mon, it's not that hard, there are lots of free viewers available. You will learn something new and next time you break a README you'll be able to fix it yourself without wasting others' time ;)

**Comment by esebastian** [comment]
I guess this doesn't apply any more.
